"""initial schema

There is deliberately no ``prediction_explanations`` table. The original plan had
one because request-time SHAP over a cohort was assumed too slow; Phase 8
measured it at 28.8 ms per student and 1.55 ms per row in batch, so the
justification did not hold. Explanations are computed on demand.

``risk_history`` is created as a VIEW, not a table: ``predictions`` is already
unique on (student, checkpoint, model version), so a history table would
duplicate every fact and create a way for the two to disagree.

Revision ID: 02a2cc279558
Revises:
Create Date: 2026-09-27 14:00:39.005293
"""

from __future__ import annotations

import sqlalchemy as sa
from backend.app.db.models import DROP_RISK_HISTORY_VIEW_SQL, RISK_HISTORY_VIEW_SQL

# Autogenerate emits `postgresql.JSONB(astext_type=Text())` for the JSON
# columns, so both names have to be in scope here.
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "02a2cc279558"
down_revision: str | None = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("resource", sa.String(length=128), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_actor_time", "audit_log", ["actor", "occurred_at"], unique=False)
    op.create_index(
        "ix_audit_resource_time", "audit_log", ["resource", "occurred_at"], unique=False
    )
    op.create_table(
        "model_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("model_type", sa.String(length=32), nullable=False),
        sa.Column("trained_at", sa.String(length=64), nullable=False),
        sa.Column("git_commit", sa.String(length=64), nullable=True),
        sa.Column("package_version", sa.String(length=32), nullable=True),
        sa.Column("n_features", sa.Integer(), nullable=False),
        sa.Column("train_data_hash", sa.String(length=64), nullable=False),
        sa.Column("imbalance_strategy", sa.String(length=32), nullable=False),
        sa.Column("calibration_method", sa.String(length=64), nullable=False),
        sa.Column(
            "metrics",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "feature_names",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_model_versions_version"), "model_versions", ["version"], unique=True)
    op.create_table(
        "students",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_code", sa.String(length=32), nullable=False),
        sa.Column("code_module", sa.String(length=16), nullable=False),
        sa.Column("code_presentation", sa.String(length=16), nullable=False),
        sa.Column("source_student_id", sa.Integer(), nullable=False),
        sa.Column("data_source", sa.String(length=16), nullable=False),
        sa.Column("module_presentation_length", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "data_source IN ('real_oulad', 'synthetic')", name="ck_students_data_source"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "code_module", "code_presentation", "source_student_id", name="uq_student_enrolment"
        ),
    )
    op.create_index(
        "ix_students_cohort", "students", ["code_module", "code_presentation"], unique=False
    )
    op.create_index(op.f("ix_students_student_code"), "students", ["student_code"], unique=True)
    op.create_table(
        "threshold_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("calibrated", sa.Boolean(), nullable=False),
        sa.Column("alert_budget", sa.Float(), nullable=True),
        sa.Column(
            "bands",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("hashed_password", sa.String(length=256), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('admin', 'counsellor', 'analyst')", name="ck_user_role"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "assessment_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("assessment_id", sa.Integer(), nullable=False),
        sa.Column("assessment_type", sa.String(length=8), nullable=False),
        sa.Column("due_day", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("date_submitted", sa.Integer(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("is_banked", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("student_id", "assessment_id", name="uq_assessment_student"),
    )
    op.create_index(
        "ix_assessment_student_due", "assessment_records", ["student_id", "due_day"], unique=False
    )
    op.create_table(
        "engagement_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("course_day", sa.Integer(), nullable=False),
        sa.Column("clicks", sa.Integer(), nullable=False),
        sa.Column("distinct_resources", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("student_id", "course_day", name="uq_engagement_student_day"),
    )
    op.create_index(
        "ix_engagement_student_day",
        "engagement_records",
        ["student_id", "course_day"],
        unique=False,
    )
    op.create_table(
        "interventions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("intervention_key", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("matched_factor", sa.String(length=64), nullable=True),
        sa.Column("assigned_to", sa.String(length=64), nullable=True),
        sa.Column("assigned_by", sa.String(length=64), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("outcome", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('recommended', 'assigned', 'in_progress', 'completed')",
            name="ck_intervention_status",
        ),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_interventions_student", "interventions", ["student_id", "status"], unique=False
    )
    op.create_table(
        "predictions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("model_version_id", sa.Integer(), nullable=False),
        sa.Column("threshold_config_id", sa.Integer(), nullable=False),
        sa.Column("checkpoint_day", sa.Integer(), nullable=False),
        sa.Column("horizon_days", sa.Integer(), nullable=False),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.Column("band", sa.String(length=16), nullable=False),
        sa.Column("features_hash", sa.String(length=64), nullable=False),
        sa.Column("label", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "band IN ('low', 'medium', 'high', 'critical')", name="ck_prediction_band"
        ),
        sa.CheckConstraint(
            "probability >= 0 AND probability <= 1", name="ck_prediction_probability"
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
        ),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["threshold_config_id"],
            ["threshold_configs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "student_id", "checkpoint_day", "model_version_id", name="uq_prediction_scope"
        ),
    )
    op.create_index(
        "ix_predictions_student_checkpoint",
        "predictions",
        ["student_id", "checkpoint_day"],
        unique=False,
    )
    op.create_index(
        "ix_predictions_upper_bands",
        "predictions",
        ["band", "probability"],
        unique=False,
        postgresql_where=sa.text("band IN ('high', 'critical')"),
    )
    op.create_table(
        "student_demographics",
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("gender", sa.String(length=16), nullable=True),
        sa.Column("age_band", sa.String(length=16), nullable=True),
        sa.Column("imd_band", sa.String(length=16), nullable=True),
        sa.Column("disability", sa.String(length=8), nullable=True),
        sa.Column("region", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("student_id"),
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("prediction_id", sa.Integer(), nullable=False),
        sa.Column("checkpoint_day", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.Column("previous_probability", sa.Float(), nullable=True),
        sa.Column("band", sa.String(length=16), nullable=False),
        sa.Column("acknowledged", sa.Boolean(), nullable=False),
        sa.Column("acknowledged_by", sa.String(length=64), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reason IN ('band_escalated', 'rapid_increase', 'sustained_increase')",
            name="ck_alert_reason",
        ),
        sa.ForeignKeyConstraint(["prediction_id"], ["predictions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("prediction_id", "reason", name="uq_alert_prediction_reason"),
    )
    op.create_index(
        "ix_alerts_queue", "alerts", ["acknowledged", "severity", "probability"], unique=False
    )
    # `risk_history` holds no facts of its own; see the module docstring.
    op.execute(RISK_HISTORY_VIEW_SQL)
    # ### end Alembic commands ###


def downgrade() -> None:
    # The view depends on predictions, so it is dropped first.
    op.execute(DROP_RISK_HISTORY_VIEW_SQL)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_alerts_queue", table_name="alerts")
    op.drop_table("alerts")
    op.drop_table("student_demographics")
    op.drop_index(
        "ix_predictions_upper_bands",
        table_name="predictions",
        postgresql_where=sa.text("band IN ('high', 'critical')"),
    )
    op.drop_index("ix_predictions_student_checkpoint", table_name="predictions")
    op.drop_table("predictions")
    op.drop_index("ix_interventions_student", table_name="interventions")
    op.drop_table("interventions")
    op.drop_index("ix_engagement_student_day", table_name="engagement_records")
    op.drop_table("engagement_records")
    op.drop_index("ix_assessment_student_due", table_name="assessment_records")
    op.drop_table("assessment_records")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_table("threshold_configs")
    op.drop_index(op.f("ix_students_student_code"), table_name="students")
    op.drop_index("ix_students_cohort", table_name="students")
    op.drop_table("students")
    op.drop_index(op.f("ix_model_versions_version"), table_name="model_versions")
    op.drop_table("model_versions")
    op.drop_index("ix_audit_resource_time", table_name="audit_log")
    op.drop_index("ix_audit_actor_time", table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
