"""Build the model-ready feature matrix and the train/validation/test split.

Raw population -> as-of features -> chronological split with student-overlap
resolution -> ``data/processed/``.

The cohort z-score transformer is deliberately **not** applied here. It is
fitted state, so it belongs inside the per-fold ``Pipeline`` built in Phase 5
(ADR-0003 control #4); fitting it on the full frame at this stage would be
preprocessing leakage.

Usage::

    python scripts/build_features.py
"""

from __future__ import annotations

import argparse

import pandas as pd

from dropout_ews.config.settings import DATA_DIR, REPORTS_DIR
from dropout_ews.data.checkpoints import build_checkpoint_rows
from dropout_ews.evaluation.splits import (
    assert_no_group_leakage_in_folds,
    grouped_cv_splits,
    make_temporal_split,
)
from dropout_ews.features.builder import FeatureBuilder

FEATURES_PARQUET = DATA_DIR / "processed" / "features.parquet"
SPLIT_PARQUET = DATA_DIR / "processed" / "split.parquet"
SPLIT_REPORT = REPORTS_DIR / "split_report.md"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cv-folds", type=int, default=5)
    args = parser.parse_args()

    print("[1/4] Building the labelled population...")
    population, population_report = build_checkpoint_rows()
    print(f"      {len(population):,} rows, {population_report.positive_rate:.2%} positive")

    print("[2/4] Building as-of features...")
    feature_set = FeatureBuilder().build(population)
    frame = feature_set.frame
    print(f"      {len(feature_set.feature_names)} features")

    print("[3/4] Splitting chronologically and resolving student overlap...")
    split = make_temporal_split(population)
    summary = split.summary(population)
    print(summary.to_string(index=False))

    folds = grouped_cv_splits(population, split.train, n_splits=args.cv_folds)
    assert_no_group_leakage_in_folds(population, split.train, folds)
    print(f"      {len(folds)} grouped CV folds, no student leakage")

    print("[4/4] Writing outputs...")
    # Features plus everything the trainer needs. `label` and
    # `date_unregistration` ride along but are excluded from the matrix by
    # `feature_names`; a test asserts they never reach a model.
    out = frame.copy()
    out["label"] = population["label"].to_numpy()
    out["code_presentation_order"] = population["code_presentation"].to_numpy()
    out["date_unregistration"] = population["date_unregistration"].to_numpy()

    assignment = pd.Series("unused", index=population.index, dtype="object")
    assignment.loc[split.train] = "train"
    assignment.loc[split.validation] = "validation"
    assignment.loc[split.test] = "test"
    assignment.loc[split.dropped_overlap] = "dropped_overlap"
    out["split"] = assignment.to_numpy()

    FEATURES_PARQUET.parent.mkdir(parents=True, exist_ok=True)
    out.to_parquet(FEATURES_PARQUET, index=False, compression="zstd")
    pd.DataFrame({"feature_name": feature_set.feature_names}).to_parquet(SPLIT_PARQUET, index=False)

    SPLIT_REPORT.parent.mkdir(parents=True, exist_ok=True)
    SPLIT_REPORT.write_text(
        "# Split report\n\n"
        "Generated by `scripts/build_features.py`. Design and rationale:\n"
        "[ADR-0003](../docs/adr/0003-leakage-controls-and-splitting.md).\n\n"
        "Chronological by presentation, with students appearing in an earlier\n"
        "split removed from the later one. 7.9% of OULAD students span\n"
        "presentations, so chronology alone leaks students.\n\n"
        + summary.to_markdown(index=False)
        + "\n\n- Features: "
        + f"**{len(feature_set.feature_names)}**\n"
        + f"- Grouped CV folds on the training split: **{len(folds)}**\n"
        + "- Student overlap across any two splits: **0** (asserted)\n",
        encoding="utf-8",
    )

    print(f"      {FEATURES_PARQUET}")
    print(f"      {SPLIT_REPORT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
