"""Generate the synthetic longitudinal cohort (Track B).

Supplies the semester GPA, backlog, and subject-wise attendance dimensions
OULAD does not contain, as a clearly-labelled separate cohort rather than
fabricated columns on real students.

**Metrics computed on this data measure pipeline correctness, not predictive
performance.** See ADR-0002 and the module docstring of
``dropout_ews.data.synthetic`` for the published generating process and the
circularity caveat.

Usage::

    python scripts/generate_synthetic_cohort.py
    python scripts/generate_synthetic_cohort.py --students 10000 --seed 7
"""

from __future__ import annotations

import argparse
import json

from dropout_ews.config.settings import DATA_DIR, REPORTS_DIR
from dropout_ews.data.synthetic import (
    SyntheticCohortGenerator,
    SyntheticConfig,
    build_synthetic_checkpoints,
)

OUTPUT_DIR = DATA_DIR / "interim" / "synthetic"
REPORT_PATH = REPORTS_DIR / "synthetic_cohort_report.md"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--students", type=int, default=4_000)
    parser.add_argument("--semesters", type=int, default=8)
    parser.add_argument("--seed", type=int, default=20260925)
    parser.add_argument(
        "--dropout-rate",
        type=float,
        default=0.22,
        help="target overall dropout rate; the hazard intercept is calibrated to it",
    )
    args = parser.parse_args()

    config = SyntheticConfig(
        n_students=args.students,
        n_semesters=args.semesters,
        seed=args.seed,
        target_dropout_rate=args.dropout_rate,
    )

    print("Generating synthetic cohort (calibrating hazard intercept)...")
    cohort = SyntheticCohortGenerator(config).generate()
    checkpoints = build_synthetic_checkpoints(cohort)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    tables = {
        "students": cohort.students,
        "semester_records": cohort.semester_records,
        "subject_attendance": cohort.subject_attendance,
        "checkpoints": checkpoints,
    }
    for name, frame in tables.items():
        path = OUTPUT_DIR / f"{name}.parquet"
        frame.to_parquet(path, index=False, compression="zstd")
        print(f"  {name:<20} {len(frame):>8,} rows  ->  {path.name}")

    calibration = cohort.calibration
    positive_rate = float(checkpoints["label"].mean())
    dropout_rate = float(cohort.students["dropout_semester"].notna().mean())

    by_shape = (
        cohort.students.assign(dropped=cohort.students["dropout_semester"].notna())
        .groupby("trajectory_shape")["dropped"]
        .agg(["size", "mean"])
    )

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Synthetic cohort report",
        "",
        "> **Synthetic data. Not real students.** Metrics computed on this cohort",
        "> measure pipeline correctness, not real-world predictive performance.",
        "> The generating process deliberately encodes the relationships the",
        "> features are designed to detect, so a model scores well on it almost by",
        "> construction. See ADR-0002.",
        "",
        f"Generated by `scripts/generate_synthetic_cohort.py` with seed `{config.seed}`.",
        "",
        "## Calibration",
        "",
        "| Parameter | Value |",
        "|---|---:|",
        f"| Students | {config.n_students:,} |",
        f"| Semesters | {config.n_semesters} |",
        f"| Target dropout rate | {config.target_dropout_rate:.1%} |",
        f"| Achieved dropout rate | {dropout_rate:.2%} |",
        f"| Calibrated hazard intercept | {calibration['hazard_intercept']} |",
        "",
        "The hazard intercept is found by bisection rather than hand-tuned, so the",
        "configured dropout rate keeps its meaning if any other coefficient changes.",
        "",
        "## Trajectory shapes",
        "",
        "| Shape | Students | Dropout rate |",
        "|---|---:|---:|",
    ]
    for shape, row in by_shape.iterrows():
        lines.append(f"| {shape} | {int(row['size']):,} | {row['mean']:.1%} |")
    lines += [
        "",
        "A negative effort drift is what produces genuinely *declining* students,",
        "as distinct from students who are uniformly weak throughout. Detecting the",
        "former is the point of the trend features.",
        "",
        "## Checkpoint population",
        "",
        f"- Rows: **{len(checkpoints):,}**",
        f"- Positives: **{int(checkpoints['label'].sum()):,}**",
        f"- Positive rate: **{positive_rate:.2%}**",
        "",
        "| Semester | Rows | Positives | Positive rate |",
        "|---:|---:|---:|---:|",
    ]
    grouped = checkpoints.groupby("semester")["label"].agg(["size", "sum", "mean"])
    for semester, row in grouped.iterrows():
        lines.append(
            f"| {semester} | {int(row['size']):,} | {int(row['sum']):,} | {row['mean']:.2%} |"
        )
    lines.append("")
    REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")

    (OUTPUT_DIR / "calibration.json").write_text(
        json.dumps(calibration, indent=2), encoding="utf-8"
    )

    print(f"\nDropout rate: {dropout_rate:.2%} (target {config.target_dropout_rate:.1%})")
    print(f"Checkpoint positive rate: {positive_rate:.2%}")
    print(f"Report: {REPORT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
